const styles = { page: { minHeight: "100vh", background: "#F3F0EC", color: "#2F3A3F", fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" }, header: { background: "#2F3A3F", color: "#FFF", padding: "18px 22px", borderBottom: "1px solid rgba(255,255,255,.1)" }, wrap: { maxWidth: 900, margin: "0 auto", padding: "55px 22px 75px" }, card: { background: "#FFF", border: "1px solid #DAD5CF", borderRadius: 18, padding: "34px clamp(22px,5vw,48px)", boxShadow: "0 14px 34px rgba(47,58,63,.08)" }, eyebrow: { color: "#8B1E3F", fontSize: 10, fontWeight: 900, letterSpacing: 1.5 }, h1: { margin: "10px 0 8px", fontSize: "clamp(32px,5vw,48px)", lineHeight: 1.05 }, h2: { margin: "30px 0 8px", fontSize: 20 }, p: { color: "#5F696E", fontSize: 13.5, lineHeight: 1.7, margin: "8px 0" }, ul: { color: "#5F696E", fontSize: 13.5, lineHeight: 1.7, paddingLeft: 22 }, note: { background: "#F4E9EC", border: "1px solid #DFC8CF", borderRadius: 12, padding: 15, color: "#6B3D4A", fontSize: 12.5, lineHeight: 1.55 } };

export default function BizzibuddiPrivacyPage() {
  return <div style={styles.page}>
    <header style={styles.header}><div style={{ maxWidth: 900, margin: "0 auto", display: "flex", justifyContent: "space-between", alignItems: "center" }}><a href="/bizzibuddi" style={{ color: "#FFF", textDecoration: "none", fontWeight: 900, letterSpacing: 1.8 }}>bizzibuddi</a><a href="/bizzibuddi" style={{ color: "#C7CDCF", textDecoration: "none", fontSize: 12 }}>← Back to bizzibuddi</a></div></header>
    <main style={styles.wrap}><article style={styles.card}>
      <div style={styles.eyebrow}>BIZZIBUDDI PRIVACY</div><h1 style={styles.h1}>Privacy Policy</h1><p style={styles.p}><strong>Development draft.</strong> This sample policy is intended as a starting point for bizzibuddi, an Australian business-management software service. It must be reviewed against the final legal entity, data flows, service providers, storage locations and applicable privacy obligations before publication.</p>
      <p style={styles.p}>Last updated: September 2026</p>
      <h2 style={styles.h2}>1. Who we are</h2><p style={styles.p}>bizzibuddi is an online platform designed to help businesses manage people, jobs, appointments, production, finance and reporting. This policy explains how information is collected, used, stored and handled when you use bizzibuddi.</p>
      <h2 style={styles.h2}>2. Information we collect</h2><p style={styles.p}>Depending on how you use bizzibuddi, we may collect:</p><ul style={styles.ul}><li>account details such as your name, business name, email address and login information;</li><li>billing and subscription information, generally processed through a payment provider;</li><li>business information you enter into your workspace;</li><li>customer, supplier, staff and contact information entered by you;</li><li>job, appointment, production, quote, invoice and payment records;</li><li>technical information such as device, browser, log, security and usage information; and</li><li>information you provide when contacting support.</li></ul>
      <h2 style={styles.h2}>3. How we collect information</h2><p style={styles.p}>Information may be collected directly from you when you create an account, configure your workspace, enter business records, contact support or otherwise use bizzibuddi. Some technical information may be collected automatically when the service is accessed.</p>
      <h2 style={styles.h2}>4. Why we use information</h2><p style={styles.p}>We may use information to provide and operate bizzibuddi, authenticate users, process subscriptions, maintain security, provide support, improve the service, prevent misuse, communicate important service information and meet legal obligations.</p>
      <h2 style={styles.h2}>5. Business data stored in bizzibuddi</h2><p style={styles.p}>When you use bizzibuddi to store information about your customers, suppliers, staff or other people, you remain responsible for ensuring that you have the appropriate authority to collect and use that information. bizzibuddi processes that information to provide the services you request and for the other purposes described in this policy.</p>
      <h2 style={styles.h2}>6. Storage and security</h2><p style={styles.p}>bizzibuddi uses reasonable technical and organisational measures intended to protect information against unauthorised access, loss, misuse and disclosure. No internet-based service can guarantee absolute security.</p>
      <h2 style={styles.h2}>7. Service providers</h2><p style={styles.p}>bizzibuddi may use trusted third-party providers for functions such as hosting, databases, authentication, payments, email, analytics, backups and infrastructure. Providers may process information on bizzibuddi's behalf and may have their own privacy terms.</p>
      <h2 style={styles.h2}>8. Disclosure of information</h2><p style={styles.p}>We may disclose information to service providers where necessary to operate bizzibuddi, where you direct us to do so, where required by law, or where reasonably necessary to protect the security and integrity of the service.</p>
      <h2 style={styles.h2}>9. International handling</h2><p style={styles.p}>Some bizzibuddi service providers may store or process information outside Australia. Before publication, this section should be updated to identify the countries or regions involved and the safeguards used for relevant international disclosures.</p>
      <h2 style={styles.h2}>10. Access and correction</h2><p style={styles.p}>You may request access to personal information we hold about you and ask us to correct information that is inaccurate, subject to applicable legal requirements and reasonable identity verification.</p>
      <h2 style={styles.h2}>11. Complaints</h2><p style={styles.p}>If you have a privacy concern or complaint, contact bizzibuddi using the published support or privacy contact details. We will review and respond to complaints within a reasonable period. Where applicable, you may also have the right to complain to the Office of the Australian Information Commissioner.</p>
      <h2 style={styles.h2}>12. Retention and deletion</h2><p style={styles.p}>We retain information for as long as reasonably necessary to provide the service, maintain security, meet contractual and legal obligations, resolve disputes and maintain appropriate business records. Specific retention periods should be documented before final publication.</p>
      <h2 style={styles.h2}>13. Cookies and similar technologies</h2><p style={styles.p}>bizzibuddi may use cookies or similar technologies required for authentication, security, preferences and service functionality. If analytics or advertising technologies are introduced, this policy should be updated to describe them and any applicable choices.</p>
      <h2 style={styles.h2}>14. Changes to this policy</h2><p style={styles.p}>This policy may be updated as bizzibuddi develops or legal and operational requirements change. Material changes will be communicated through appropriate channels where required.</p>
      <h2 style={styles.h2}>15. Contact</h2><p style={styles.p}>Privacy questions, access requests and complaints should be sent to the privacy contact published by the bizzibuddi operating entity.</p>
      <div style={{ ...styles.note, marginTop: 28 }}>Before launch, replace this draft with the final entity name, contact details, applicable privacy-law status, actual hosting and storage locations, payment and analytics providers, international disclosure details, retention periods and formal complaint process.</div>
    </article></main>
  </div>;
}
