const BRAND = { crimson: "#C4003D", crimsonDark: "#780024", accent: "#FF174F", background: "#08090D", surface: "#12141B", surfaceRaised: "#1A0D14", paper: "#F4F1F3", ink: "#FFFFFF", muted: "#B8AEB5" };

const styles = { page: { minHeight: "100vh", background: BRAND.background, color: BRAND.ink, fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" }, header: { background: BRAND.surfaceRaised, color: "#FFF", padding: "18px 22px", borderBottom: `2px solid ${BRAND.crimson}` }, wrap: { maxWidth: 900, margin: "0 auto", padding: "55px 22px 75px" }, card: { background: BRAND.surface, border: `1px solid ${BRAND.crimson}`, borderRadius: 18, padding: "34px clamp(22px,5vw,48px)", boxShadow: "0 18px 48px rgba(0,0,0,.45)" }, eyebrow: { color: BRAND.accent, fontSize: 10, fontWeight: 900, letterSpacing: 1.5 }, h1: { margin: "10px 0 8px", fontSize: "clamp(32px,5vw,48px)", lineHeight: 1.05 }, h2: { margin: "30px 0 8px", fontSize: 20, color: "#FFFFFF" }, p: { color: "#D8D0D5", fontSize: 13.5, lineHeight: 1.7, margin: "8px 0" }, ul: { color: "#D8D0D5", fontSize: 13.5, lineHeight: 1.7, paddingLeft: 22 }, note: { background: BRAND.surfaceRaised, border: `1px solid ${BRAND.accent}`, borderRadius: 12, padding: 15, color: "#FFD7E0", fontSize: 12.5, lineHeight: 1.55 } };
const footerLink = { color: "#FFB5C7", textDecoration: "none" };

function Footer() { return <footer style={{ background: "#050609", color: "#AFA3AB", padding: "30px 22px", borderTop: `2px solid ${BRAND.crimson}` }}><div style={{ maxWidth: 900, margin: "0 auto" }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 18, flexWrap: "wrap" }}><a href="/bizzibuddi" style={{ color: "#FFF", textDecoration: "none", fontWeight: 900, letterSpacing: 1.8 }}>BizziBuddi</a><div style={{ display: "flex", gap: 16, flexWrap: "wrap", fontSize: 12 }}><a href="/bizzibuddi" style={footerLink}>Home</a><a href="/bizzibuddi/privacy" style={footerLink}>Privacy Policy</a><a href="/bizzibuddi/terms" style={footerLink}>Terms &amp; Conditions</a></div></div><div style={{ marginTop: 18, paddingTop: 14, borderTop: "1px solid rgba(255,255,255,.16)", display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", fontSize: 10, color: "#8E7C86" }}><span>© {new Date().getFullYear()} BizziBuddi. All rights reserved.</span><span>Business management, all in one place.</span></div></div></footer>; }

export default function BizzibuddiTermsPage() {
  return <div style={styles.page}>
    <header style={styles.header}><div style={{ maxWidth: 900, margin: "0 auto", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, flexWrap: "wrap" }}><a href="/bizzibuddi" style={{ color: "#FFF", textDecoration: "none", fontWeight: 900, letterSpacing: 1.8 }}>BizziBuddi</a><a href="/bizzibuddi" style={{ color: "#FFB5C7", textDecoration: "none", fontSize: 12 }}>← Back to BizziBuddi</a></div></header>
    <main style={styles.wrap}><article style={styles.card}>
      <div style={styles.eyebrow}>BIZZIBUDDI TERMS</div><h1 style={styles.h1}>Terms &amp; Conditions</h1><p style={styles.p}><strong>Development draft.</strong> These sample terms are intended as a starting point for BizziBuddi, an Australian business-management software service. They should be reviewed and finalised for the operating legal entity, billing arrangements, technical architecture and applicable law before publication.</p>
      <p style={styles.p}>Last updated: September 2026</p>
      <h2 style={styles.h2}>1. About BizziBuddi</h2><p style={styles.p}>BizziBuddi provides online business-management tools that may include customer records, jobs, appointments, production workflows, financial records, reporting and related business features. By creating an account or using BizziBuddi, you agree to these Terms.</p>
      <h2 style={styles.h2}>2. Your account</h2><p style={styles.p}>You are responsible for providing accurate account information, keeping login credentials secure and ensuring that people using your account are authorised to do so. You must promptly notify BizziBuddi of suspected unauthorised access.</p>
      <h2 style={styles.h2}>3. Your workspace and business data</h2><p style={styles.p}>Your workspace may contain information about your business, customers, suppliers, jobs, appointments, payments and other records that you enter or upload.</p><p style={styles.p}><strong>Your business data is yours.</strong> You retain your rights in data you provide to BizziBuddi. You authorise BizziBuddi to process that data as reasonably necessary to provide, secure, maintain and improve the service.</p><p style={styles.p}>You are responsible for ensuring that you have the appropriate authority to collect, store and use information you enter about other people.</p>
      <h2 style={styles.h2}>4. Plans and subscriptions</h2><p style={styles.p}>BizziBuddi may offer different workspace plans with different features, limits and prices. Plan features and pricing will be displayed before purchase. Where a paid subscription renews automatically, the renewal frequency, price and cancellation terms will be clearly disclosed.</p>
      <h2 style={styles.h2}>5. Fees and payments</h2><p style={styles.p}>Paid services are charged according to the selected plan and billing arrangement. Applicable taxes and unavoidable charges will be disclosed as required. BizziBuddi may use a third-party payment provider to process payments.</p>
      <h2 style={styles.h2}>6. Cancellation</h2><p style={styles.p}>You may cancel a paid subscription using the available account or billing controls, subject to the terms presented when you subscribe. Cancellation should stop future renewal charges, while access to paid features may continue until the end of the relevant paid period unless otherwise stated.</p>
      <h2 style={styles.h2}>7. Suspension and termination</h2><p style={styles.p}>BizziBuddi may suspend or terminate access where reasonably necessary for security, legal compliance, non-payment, misuse of the service or material breach of these Terms. Where practical, BizziBuddi will provide notice and an opportunity to resolve the issue.</p>
      <h2 style={styles.h2}>8. Data export and closure</h2><p style={styles.p}>BizziBuddi intends to provide reasonable ways to export business information, subject to the capabilities of the applicable plan and technical limitations. On account closure, data may be retained for a limited period where required for security, legal, accounting or legitimate operational purposes before deletion.</p>
      <h2 style={styles.h2}>9. Acceptable use</h2><p style={styles.p}>You must not use BizziBuddi to break the law, infringe another person's rights, distribute malicious software, attempt to gain unauthorised access, interfere with the service or misuse another user's information.</p>
      <h2 style={styles.h2}>10. Third-party services</h2><p style={styles.p}>BizziBuddi may integrate with third-party services such as payment, email, calendar, hosting or analytics providers. Those services may have their own terms and privacy policies. BizziBuddi is not responsible for independent third-party services outside its reasonable control.</p>
      <h2 style={styles.h2}>11. Availability and changes</h2><p style={styles.p}>BizziBuddi aims to provide a reliable service but does not guarantee uninterrupted availability. Features may change as the service develops. Material changes to these Terms will be communicated through appropriate channels where required.</p>
      <h2 style={styles.h2}>12. Australian Consumer Law</h2><p style={styles.p}>Nothing in these Terms excludes, restricts or modifies any right, guarantee, warranty or remedy that cannot lawfully be excluded under the <em>Competition and Consumer Act 2010</em> (Cth), including the Australian Consumer Law.</p>
      <h2 style={styles.h2}>13. Intellectual property</h2><p style={styles.p}>BizziBuddi and its software, branding, interfaces and underlying technology remain the property of BizziBuddi or its licensors. These Terms give you a limited right to use the service for your business while your account is active.</p>
      <h2 style={styles.h2}>14. Limitation of liability</h2><p style={styles.p}>To the maximum extent permitted by law, BizziBuddi's liability will be limited in accordance with applicable law. Nothing in this section is intended to exclude liability that cannot legally be excluded.</p>
      <h2 style={styles.h2}>15. Governing law</h2><p style={styles.p}>These Terms are intended to be governed by the laws of Australia and the applicable laws of the state or territory in which the BizziBuddi operating entity is established, subject to mandatory legal rights.</p>
      <h2 style={styles.h2}>16. Contact</h2><p style={styles.p}>Questions about these Terms should be directed to the BizziBuddi operator using the contact details published with the service.</p>
      <div style={{ ...styles.note, marginTop: 28 }}>Before launch, replace this draft with the final legal entity name, ABN/ACN where appropriate, registered/business address, contact email, payment terms, refund policy, data-retention rules and any specific service-level commitments.</div>
    </article></main>
    <Footer />
  </div>;
}
