import { useState } from "react";
import BizzibuddiTermsPage from "./BizzibuddiTermsPage";
import BizzibuddiPrivacyPage from "./BizzibuddiPrivacyPage";

const RED = "#FF174F";
const RED_DARK = "#C4003D";
const BG = "#08090D";
const SURFACE = "#12141B";
const TEXT = "#FFFFFF";
const MUTED = "#B8B0B8";

const plans = [
  { name: "Free Workspace", price: "$0", period: "forever", description: "A simple starting point for independent operators.", features: ["People & contacts", "Basic jobs", "Calendar", "Dashboard"] },
  { name: "Professional Workspace", price: "$9", period: "/ month", description: "For established service businesses and solo professionals.", features: ["Everything in Free", "Advanced scheduling", "Payments & invoices", "Automation"] },
  { name: "Team Workspace", price: "$19", period: "/ month", description: "For small teams working together in one place.", features: ["Everything in Professional", "Shared workspace", "Team workflow", "Production tracking"], popular: true },
  { name: "Business Workspace", price: "$39", period: "/ month", description: "For growing businesses needing deeper control.", features: ["Everything in Team", "Advanced reporting", "Priority features", "Professional controls"] },
];

const features = [
  ["01", "People", "Clients, contacts and history in one place."],
  ["02", "Jobs", "Take work from quote to completion."],
  ["03", "Production", "See what needs doing and what comes next."],
  ["04", "Calendar", "Appointments, bookings and important dates."],
  ["05", "Finance", "Quotes, invoices, payments and balances."],
  ["06", "Reports", "Useful information about your business."],
];

const buttonBase = { borderRadius: 10, minHeight: 44, padding: "0 18px", fontWeight: 800, fontSize: 13, cursor: "pointer", transition: "transform .18s ease, box-shadow .18s ease, background .18s ease" };
const eyebrow = { color: RED, fontSize: 10, fontWeight: 900, letterSpacing: 1.5 };
const eyebrowDark = { color: RED, fontSize: 10, fontWeight: 900, letterSpacing: 1.5 };
const heading = { margin: "10px 0 0", fontSize: "clamp(30px, 4vw, 46px)", lineHeight: 1.08, letterSpacing: -1.2, color: TEXT };
const lead = { maxWidth: 650, margin: "12px 0 0", color: MUTED, fontSize: 14, lineHeight: 1.6 };
const panel = { background: SURFACE, border: `1px solid ${RED}`, borderRadius: 20, boxShadow: "0 20px 48px rgba(0,0,0,.42)", position: "relative", overflow: "hidden", color: TEXT };
const footerLink = { color: RED, textDecoration: "none", fontWeight: 800 };
const footerButton = { border: "none", background: "transparent", color: RED, padding: 0, textAlign: "left", font: "inherit", fontWeight: 800, cursor: "pointer" };

function scrollToId(id) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }

function Logo() {
  return <div style={{ display: "flex", alignItems: "center", gap: 10, whiteSpace: "nowrap" }}><span style={{ width: 30, height: 30, border: "2px solid #FFF", borderRadius: 9, display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 900, transform: "rotate(45deg)", background: RED_DARK }}><span style={{ transform: "rotate(-45deg)" }}>B</span></span><span style={{ fontSize: 21, fontWeight: 900, letterSpacing: 1.8 }}>{"BizziBuddi"}</span></div>;
}

function CtaButton({ children, secondary = false, onClick }) {
  return <button type="button" onClick={onClick} style={{ ...buttonBase, border: secondary ? `1px solid ${RED}` : "none", background: secondary ? "transparent" : RED, color: "#FFF", boxShadow: secondary ? "none" : `0 10px 28px rgba(255,23,79,.28)` }}>{children}</button>;
}

function Footer() {
  return <footer style={{ background: "#050609", color: "#D7D0D5", padding: "54px 22px 30px", borderTop: `3px solid ${RED}` }}><div style={{ maxWidth: 1080, margin: "0 auto" }}><div className="bizzibuddi-footer-grid" style={{ display: "grid", gridTemplateColumns: "1.3fr 1fr 1fr", gap: 34, alignItems: "start" }}><div><Logo /><div style={{ marginTop: 12, fontSize: 13, lineHeight: 1.6 }}>Streamline your business.<br />Simplify your work.</div><div style={{ marginTop: 16, color: RED, fontSize: 11, fontWeight: 900, letterSpacing: 1.1 }}>BUSINESS MANAGEMENT, ALL IN ONE PLACE.</div></div><div><div style={{ color: TEXT, fontSize: 12, fontWeight: 900, letterSpacing: 1.2, textTransform: "uppercase", marginBottom: 14 }}>Quick Links</div><div style={{ display: "grid", gap: 11, fontSize: 13 }}><a href="/bizzibuddi" style={footerLink} className="bizzibuddi-footer-link">Home</a><button type="button" onClick={() => scrollToId("why")} style={footerButton} className="bizzibuddi-footer-link">Why BizziBuddi</button><button type="button" onClick={() => scrollToId("features")} style={footerButton} className="bizzibuddi-footer-link">Features</button><button type="button" onClick={() => scrollToId("pricing")} style={footerButton} className="bizzibuddi-footer-link">Pricing</button></div></div><div><div style={{ color: TEXT, fontSize: 12, fontWeight: 900, letterSpacing: 1.2, textTransform: "uppercase", marginBottom: 14 }}>Account</div><div style={{ display: "grid", gap: 11, fontSize: 13 }}><a href="/login" style={footerLink} className="bizzibuddi-footer-link">Sign In</a><a href="#pricing" style={footerLink} className="bizzibuddi-footer-link">Start Free</a></div></div></div><div style={{ marginTop: 38, paddingTop: 18, borderTop: "1px solid rgba(255,255,255,.22)", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 14, flexWrap: "wrap", fontSize: 12 }}><div style={{ display: "flex", alignItems: "center", gap: 18, flexWrap: "wrap" }}><a href="/bizzibuddi/terms" style={footerLink} className="bizzibuddi-footer-link">Terms &amp; Conditions</a><a href="/bizzibuddi/privacy" style={footerLink} className="bizzibuddi-footer-link">Privacy Policy</a><span style={{ color: "#D7D0D5" }}>© {new Date().getFullYear()} BizziBuddi. All rights reserved.</span></div></div><div style={{ marginTop: 18, textAlign: "center", fontSize: 11, color: "#AFA7AE" }}>Development site — pricing, billing and account subscriptions will be connected next.</div></div></footer>;
}

export default function BizzibuddiLandingPage() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const pathname = window.location.pathname.replace(/\/$/, "");
  if (pathname === "/bizzibuddi/terms") return <BizzibuddiTermsPage />;
  if (pathname === "/bizzibuddi/privacy") return <BizzibuddiPrivacyPage />;

  const goPricing = () => scrollToId("pricing");
  const nav = { border: "none", background: "transparent", color: "#FFFFFF", fontWeight: 800, fontSize: 12, cursor: "pointer" };
  const pillars = [["ONE PLACE", "Everything together", "Stop jumping between spreadsheets, notes and messages."], ["CLEAR WORKFLOW", "Know what is next", "Keep work moving from first contact to completion."], ["LESS ADMIN", "Get time back", "Simple tools designed around everyday business work."]];
  const reasons = [["Clarity", "See the information that matters without digging through systems."], ["Control", "Keep jobs, schedules, payments and processes organised."], ["Confidence", "Know where your work and business stand at a glance."]];

  return <div style={{ minHeight: "100vh", background: BG, color: TEXT, fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" }}>
    <style>{`button:hover,.bizzibuddi-footer-link:hover{transform:translateY(-1px);filter:brightness(1.22)}a:hover{filter:brightness(1.22)}.bizzibuddi-card:hover{transform:translateY(-3px);border-color:${RED}!important;box-shadow:0 18px 42px rgba(255,23,79,.16)!important}.bizzibuddi-footer-link{transition:filter .18s ease,transform .18s ease}@media(max-width:850px){.bizzibuddi-desktop-nav{display:none!important}.bizzibuddi-mobile-button{display:block!important}.bizzibuddi-hero-grid,.bizzibuddi-three-grid,.bizzibuddi-feature-grid{grid-template-columns:1fr!important}.bizzibuddi-plan-grid{grid-template-columns:1fr 1fr!important}.bizzibuddi-footer-grid{grid-template-columns:1fr 1fr!important}}@media(max-width:520px){.bizzibuddi-plan-grid{grid-template-columns:1fr!important}.bizzibuddi-footer-grid{grid-template-columns:1fr!important}.bizzibuddi-section-pad{padding-left:16px!important;padding-right:16px!important}}`}</style>
    <header style={{ position: "sticky", top: 0, zIndex: 20, background: "rgba(8,9,13,.98)", color: "#FFF", borderBottom: `3px solid ${RED}`, backdropFilter: "blur(12px)" }}><div style={{ maxWidth: 1120, margin: "0 auto", padding: "12px 22px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 18 }}><a href="/bizzibuddi" style={{ color: "inherit", textDecoration: "none" }}><Logo /></a><nav className="bizzibuddi-desktop-nav" style={{ display: "flex", alignItems: "center", gap: 20 }}><button type="button" onClick={() => scrollToId("why")} style={nav}>Why BizziBuddi</button><button type="button" onClick={() => scrollToId("features")} style={nav}>Features</button><button type="button" onClick={goPricing} style={nav}>Pricing</button><CtaButton onClick={goPricing}>Start Free →</CtaButton></nav><button type="button" aria-label="Open navigation" onClick={() => setMobileOpen(v => !v)} style={{ border: `1px solid ${RED}`, background: "transparent", color: "#FFF", borderRadius: 8, minHeight: 40, padding: "0 12px", cursor: "pointer", display: "none" }} className="bizzibuddi-mobile-button">☰</button></div>{mobileOpen && <div style={{ padding: "0 22px 15px", display: "grid", gap: 9 }}><button type="button" onClick={() => { setMobileOpen(false); scrollToId("why"); }} style={nav}>Why BizziBuddi</button><button type="button" onClick={() => { setMobileOpen(false); scrollToId("features"); }} style={nav}>Features</button><button type="button" onClick={() => { setMobileOpen(false); goPricing(); }} style={nav}>Pricing</button><button type="button" onClick={() => { setMobileOpen(false); goPricing(); }} style={{ ...buttonBase, border: "none", background: RED, color: "#FFF" }}>Start Free →</button></div>}</header>
    <main>
      <section style={{ background: `linear-gradient(135deg, ${BG} 0%, ${SURFACE} 62%, #24000F 100%)`, color: "#FFF", padding: "76px 22px 64px" }}><div style={{ maxWidth: 1080, margin: "0 auto", textAlign: "center" }}><div style={eyebrowDark}>BUSINESS MANAGEMENT, SIMPLIFIED</div><h1 style={{ margin: "15px auto 0", maxWidth: 800, fontSize: "clamp(42px, 7vw, 74px)", lineHeight: .99, letterSpacing: -3 }}>Run your business.<br /><span style={{ color: RED }}>With BizziBuddi.</span></h1><p style={{ maxWidth: 680, margin: "20px auto 0", color: "#EDE6EA", fontSize: 16, lineHeight: 1.6 }}>One clear workspace for your people, jobs, production, calendar and money.</p><div style={{ marginTop: 25, display: "flex", justifyContent: "center", gap: 10, flexWrap: "wrap" }}><CtaButton onClick={goPricing}>Start with BizziBuddi Free →</CtaButton><CtaButton secondary onClick={() => scrollToId("features")}>Explore BizziBuddi</CtaButton></div><div className="bizzibuddi-hero-grid" style={{ marginTop: 42, display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 12, textAlign: "left" }}>{pillars.map(([label, title, text]) => <article key={label} className="bizzibuddi-card" style={{ background: "rgba(255,255,255,.045)", border: `1px solid ${RED}`, borderRadius: 16, padding: 20, minHeight: 125, transition: "transform .18s ease,box-shadow .18s ease,border-color .18s ease" }}><div style={eyebrowDark}>{label}</div><strong style={{ display: "block", marginTop: 9, fontSize: 16 }}>{title}</strong><p style={{ margin: "7px 0 0", color: "#E0D5DC", fontSize: 12.5, lineHeight: 1.5 }}>{text}</p></article>)}</div></div></section>
      <section id="why" style={{ maxWidth: 1080, margin: "0 auto", padding: "70px 22px" }} className="bizzibuddi-section-pad"><div style={eyebrow}>WHY BIZZIBUDDI</div><h2 style={heading}>Everything your business needs.<br />In one place.</h2><p style={lead}>BizziBuddi is built to make the everyday running of a business clearer, faster and easier to manage.</p><div className="bizzibuddi-three-grid" style={{ marginTop: 28, display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 14 }}>{reasons.map(([title, text], index) => <article key={title} className="bizzibuddi-card" style={{ ...panel, padding: 28, minHeight: 205, transition: "transform .18s ease,box-shadow .18s ease,border-color .18s ease" }}><div style={{ position: "absolute", left: 0, right: 0, top: 0, height: 5, background: RED }} /><div style={{ width: 54, height: 54, borderRadius: 15, background: "#24000F", color: RED, display: "grid", placeItems: "center", fontWeight: 900, fontSize: 17 }}>{index + 1}</div><h3 style={{ margin: "19px 0 8px", fontSize: 22 }}>{title}</h3><p style={{ margin: 0, color: MUTED, fontSize: 14, lineHeight: 1.65 }}>{text}</p></article>)}</div></section>
      <section id="features" style={{ background: "#0E1016", borderTop: `1px solid ${RED}`, borderBottom: `1px solid ${RED}`, padding: "70px 22px" }} className="bizzibuddi-section-pad"><div style={{ maxWidth: 1080, margin: "0 auto" }}><div style={eyebrow}>YOUR BUSINESS. YOUR WORKSPACE.</div><h2 style={heading}>Six essentials.<br />One powerful BizziBuddi workspace.</h2><div className="bizzibuddi-feature-grid" style={{ marginTop: 28, display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 14 }}>{features.map(([number, title, text]) => <article key={title} className="bizzibuddi-card" style={{ ...panel, padding: 22, minHeight: 155, transition: "transform .18s ease,box-shadow .18s ease,border-color .18s ease" }}><div style={{ display: "flex", justifyContent: "space-between" }}><span style={eyebrow}>{number}</span><span style={{ color: RED, fontSize: 20 }}>↗</span></div><h3 style={{ margin: "16px 0 8px", fontSize: 21 }}>{title}</h3><p style={{ margin: 0, color: MUTED, fontSize: 13.5, lineHeight: 1.65 }}>{text}</p></article>)}</div></div></section>
      <section id="pricing" style={{ background: "#0A0B10", padding: "70px 22px" }} className="bizzibuddi-section-pad"><div style={{ maxWidth: 1080, margin: "0 auto" }}><div style={{ textAlign: "center" }}><div style={eyebrow}>SIMPLE PRICING</div><h2 style={{ ...heading, marginLeft: "auto", marginRight: "auto" }}>Start free. Grow when you're ready.</h2><p style={{ ...lead, marginLeft: "auto", marginRight: "auto" }}>No complicated setup. No long-term commitment. Choose the level that fits your business.</p></div><div className="bizzibuddi-plan-grid" style={{ marginTop: 42, display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 14, alignItems: "stretch" }}>{plans.map((plan) => <article key={plan.name} className="bizzibuddi-card" style={{ ...panel, border: `1px solid ${plan.popular ? RED : "#34303A"}`, borderRadius: 14, padding: 22, transition: "transform .18s ease,box-shadow .18s ease,border-color .18s ease" }}>{plan.popular && <div style={{ margin: "-22px -22px 18px", padding: "8px 12px", background: RED, color: "#FFF", textAlign: "center", fontSize: 11, fontWeight: 900, letterSpacing: 1, textTransform: "uppercase" }}>Most popular</div>}<h3 style={{ margin: 0, fontSize: 20 }}>{plan.name}</h3><div style={{ marginTop: 18, display: "flex", alignItems: "baseline", gap: 6 }}><strong style={{ fontSize: 38 }}>{plan.price}</strong><span style={{ color: MUTED, fontSize: 12 }}>{plan.period}</span></div><p style={{ minHeight: 66, color: MUTED, fontSize: 13, lineHeight: 1.55 }}>{plan.description}</p><div style={{ display: "grid", gap: 10, minHeight: 130 }}>{plan.features.map((feature) => <div key={feature} style={{ display: "flex", gap: 8, fontSize: 13 }}><span style={{ color: RED, fontWeight: 900 }}>✓</span>{feature}</div>)}</div><button type="button" onClick={() => alert(`BizziBuddi ${plan.name} signup will be connected in the account/subscription stage.`)} style={{ width: "100%", marginTop: 22, minHeight: 44, border: `1px solid ${RED}`, borderRadius: 9, background: plan.popular ? RED : "transparent", color: "#FFF", fontWeight: 800, cursor: "pointer" }}>{plan.name === "Free Workspace" ? "Start Free" : `Choose ${plan.name.replace(" Workspace", "")}`}</button></article>)}</div><p style={{ textAlign: "center", margin: "22px 0 0", color: "#AFA7AE", fontSize: 12 }}>Prices shown are mock pricing for the BizziBuddi development site and are not yet connected to billing.</p></div></section>
      <section style={{ background: `linear-gradient(135deg, ${SURFACE}, #16000A)`, color: "#FFF", padding: "80px 22px" }}><div style={{ maxWidth: 900, margin: "0 auto", textAlign: "center" }}><div style={eyebrowDark}>READY WHEN YOU ARE</div><h2 style={{ margin: "15px 0 0", fontSize: "clamp(32px, 5vw, 52px)" }}>Your business has enough to manage.<br />BizziBuddi makes it simpler.</h2><CtaButton onClick={goPricing}>Start for free →</CtaButton></div></section>
    </main>
    <Footer />
  </div>;
}
