import { useState } from "react";
import ThriveTermsPage from "./ThriveTermsPage";
import ThrivePrivacyPage from "./ThrivePrivacyPage";

const plans = [
  { name: "Free Workspace", price: "$0", period: "forever", description: "A simple starting point for independent operators.", features: ["People & contacts", "Basic jobs", "Calendar", "Dashboard"] },
  { name: "Professional Workspace", price: "$9", period: "/ month", description: "For established service businesses and solo professionals.", features: ["Everything in Free", "Advanced scheduling", "Payments & invoices", "Automation"] },
  { name: "Team Workspace", price: "$19", period: "/ month", description: "For small teams working together in one place.", features: ["Everything in Professional", "Shared workspace", "Team workflow", "Production tracking"], popular: true },
  { name: "Business Workspace", price: "$39", period: "/ month", description: "For growing businesses needing deeper control.", features: ["Everything in Team", "Advanced reporting", "Priority features", "Professional controls"] },
];

const features = [
  ["01", "People", "Clients, contacts and history in one place."],
  ["02", "Jobs", "Take work from quote to completion."],
  ["03", "Production", "See what needs doing and what comes next."],
  ["04", "Calendar", "Appointments, bookings and important dates."],
  ["05", "Finance", "Quotes, invoices, payments and balances."],
  ["06", "Reports", "Useful information about your business."],
];

const buttonBase = { borderRadius: 10, minHeight: 44, padding: "0 18px", fontWeight: 800, fontSize: 13, cursor: "pointer", transition: "transform .18s ease, box-shadow .18s ease" };
const eyebrow = { color: "#8B1E3F", fontSize: 10, fontWeight: 900, letterSpacing: 1.5 };
const eyebrowDark = { color: "#C96A83", fontSize: 10, fontWeight: 900, letterSpacing: 1.5 };
const heading = { margin: "10px 0 0", fontSize: "clamp(30px, 4vw, 46px)", lineHeight: 1.08, letterSpacing: -1.2 };
const lead = { maxWidth: 650, margin: "12px 0 0", color: "#687178", fontSize: 14, lineHeight: 1.6 };
const panel = { background: "#FFF", border: "1px solid #DAD5CF", borderRadius: 18, boxShadow: "0 14px 34px rgba(47,58,63,.08)" };

function scrollToId(id) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
function Logo() { return <div style={{ display: "flex", alignItems: "center", gap: 10 }}><span style={{ width: 30, height: 30, border: "2px solid #FFF", borderRadius: 9, display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 900, transform: "rotate(45deg)" }}><span style={{ transform: "rotate(-45deg)" }}>T</span></span><span style={{ fontSize: 21, fontWeight: 900, letterSpacing: 2.5 }}>THRIVE</span></div>; }
function CtaButton({ children, secondary = false, onClick }) { return <button type="button" onClick={onClick} style={{ ...buttonBase, border: secondary ? "1px solid rgba(255,255,255,.28)" : "none", background: secondary ? "rgba(255,255,255,.06)" : "#C96A83", color: "#FFF", boxShadow: secondary ? "none" : "0 10px 26px rgba(201,106,131,.25)" }}>{children}</button>; }

export default function ThriveLandingPage() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const pathname = window.location.pathname.replace(/\/$/, "");
  if (pathname === "/thrive/terms") return <ThriveTermsPage />;
  if (pathname === "/thrive/privacy") return <ThrivePrivacyPage />;

  const goPricing = () => scrollToId("pricing");
  const nav = { border: "none", background: "transparent", color: "#D8DDDE", fontWeight: 700, fontSize: 12, cursor: "pointer" };

  return <div style={{ minHeight: "100vh", background: "#F3F0EC", color: "#2F3A3F", fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" }}>
    <style>{`@media(max-width:850px){.thrive-desktop-nav{display:none!important}.thrive-mobile-button{display:block!important}.thrive-hero-grid,.thrive-three-grid,.thrive-feature-grid{grid-template-columns:1fr!important}.thrive-plan-grid{grid-template-columns:1fr 1fr!important}}@media(max-width:520px){.thrive-plan-grid{grid-template-columns:1fr!important}.thrive-section-pad{padding-left:16px!important;padding-right:16px!important}}button:hover{transform:translateY(-1px)}`}</style>
    <header style={{ position: "sticky", top: 0, zIndex: 20, background: "rgba(47,58,63,.98)", color: "#FFF", borderBottom: "1px solid rgba(255,255,255,.1)", backdropFilter: "blur(12px)" }}><div style={{ maxWidth: 1120, margin: "0 auto", padding: "12px 22px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 18 }}><a href="/thrive" style={{ color: "inherit", textDecoration: "none" }}><Logo /></a><nav className="thrive-desktop-nav" style={{ display: "flex", alignItems: "center", gap: 20 }}><button type="button" onClick={() => scrollToId("why")} style={nav}>Why THRIVE</button><button type="button" onClick={() => scrollToId("features")} style={nav}>Features</button><button type="button" onClick={goPricing} style={nav}>Pricing</button><CtaButton onClick={goPricing}>Start Free →</CtaButton></nav><button type="button" aria-label="Open navigation" onClick={() => setMobileOpen(v => !v)} style={{ border: "1px solid rgba(255,255,255,.2)", background: "transparent", color: "#FFF", borderRadius: 8, minHeight: 40, padding: "0 12px", cursor: "pointer", display: "none" }} className="thrive-mobile-button">☰</button></div>{mobileOpen && <div style={{ padding: "0 22px 15px", display: "grid", gap: 7 }}><button type="button" onClick={() => { setMobileOpen(false); scrollToId("why"); }} style={nav}>Why THRIVE</button><button type="button" onClick={() => { setMobileOpen(false); scrollToId("features"); }} style={nav}>Features</button><button type="button" onClick={() => { setMobileOpen(false); goPricing(); }} style={nav}>Pricing</button><button type="button" onClick={() => { setMobileOpen(false); goPricing(); }} style={{ ...buttonBase, border: "none", background: "#C96A83", color: "#FFF" }}>Start Free →</button></div>}</header>
    <main>
      <section style={{ background: "#2F3A3F", color: "#FFF", padding: "76px 22px 64px" }}><div style={{ maxWidth: 1080, margin: "0 auto", textAlign: "center" }}><div style={eyebrowDark}>BUSINESS MANAGEMENT, SIMPLIFIED</div><h1 style={{ margin: "15px auto 0", maxWidth: 800, fontSize: "clamp(42px, 7vw, 74px)", lineHeight: .99, letterSpacing: -3 }}>Run your business.<br /><span style={{ color: "#C96A83" }}>Thrive.</span></h1><p style={{ maxWidth: 680, margin: "20px auto 0", color: "#D6DADC", fontSize: 16, lineHeight: 1.6 }}>One clear workspace for your people, jobs, production, calendar and money.</p><div style={{ marginTop: 25, display: "flex", justifyContent: "center", gap: 10, flexWrap: "wrap" }}><CtaButton onClick={goPricing}>Start with THRIVE Free →</CtaButton><CtaButton secondary onClick={() => scrollToId("features")}>Explore THRIVE</CtaButton></div><div className="thrive-hero-grid" style={{ marginTop: 42, display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 12, textAlign: "left" }}>{[["ONE PLACE","Everything together","Stop jumping between spreadsheets, notes and messages."],["CLEAR WORKFLOW","Know what is next","Keep work moving from first contact to completion."],["LESS ADMIN","Get time back","Simple tools designed around everyday business work."]].map(([label,title,text]) => <article key={label} style={{ background: "rgba(255,255,255,.055)", border: "1px solid rgba(255,255,255,.16)", borderRadius: 16, padding: 20, minHeight: 125, boxShadow: "inset 0 1px rgba(255,255,255,.04)" }}><div style={eyebrowDark}>{label}</div><strong style={{ display: "block", marginTop: 9, fontSize: 16 }}>{title}</strong><p style={{ margin: "7px 0 0", color: "#BFC5C7", fontSize: 12.5, lineHeight: 1.5 }}>{text}</p></article>)}</div></div></section>
      <section id="why" style={{ maxWidth: 1080, margin: "0 auto", padding: "70px 22px" }} className="thrive-section-pad"><div style={eyebrow}>WHY THRIVE</div><h2 style={heading}>Everything your business needs.<br />In one place.</h2><p style={lead}>THRIVE is built to make the everyday running of a business clearer, faster and easier to manage.</p><div className="thrive-three-grid" style={{ marginTop: 28, display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 14 }}>{[["Clarity","See the information that matters without digging through systems."],["Control","Keep jobs, schedules, payments and processes organised."],["Confidence","Know where your work and business stand at a glance."]].map(([title,text],i) => <article key={title} style={{ ...panel, padding: 24, minHeight: 180 }}><div style={{ width: 34, height: 34, borderRadius: 10, background: "#F0E5E8", color: "#8B1E3F", display: "grid", placeItems: "center", fontWeight: 900 }}>{i+1}</div><h3 style={{ margin: "16px 0 7px", fontSize: 19 }}>{title}</h3><p style={{ margin: 0, color: "#687178", fontSize: 13, lineHeight: 1.6 }}>{text}</p></article>)}</div></section>
      <section id="features" style={{ background: "#FFF", borderTop: "1px solid #E2DED9", borderBottom: "1px solid #E2DED9", padding: "70px 22px" }} className="thrive-section-pad"><div style={{ maxWidth: 1080, margin: "0 auto" }}><div style={eyebrow}>YOUR BUSINESS. YOUR WORKSPACE.</div><h2 style={heading}>Six essentials.<br />One simple system.</h2><div className="thrive-feature-grid" style={{ marginTop: 28, display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 14 }}>{features.map(([number,title,text]) => <article key={title} style={{ ...panel, padding: 22, minHeight: 155 }}><div style={{ display: "flex", justifyContent: "space-between" }}><span style={eyebrow}>THRIVE</span><span style={{ color: "#A6ADB0", fontSize: 11, fontWeight: 800 }}>{number}</span></div><h3 style={{ margin: "13px 0 6px", fontSize: 18 }}>{title}</h3><p style={{ margin: 0, color: "#687178", fontSize: 12.5, lineHeight: 1.55 }}>{text}</p></article>)}</div></div></section>
      <section id="pricing" style={{ background: "#E9E4DE", padding: "70px 22px" }} className="thrive-section-pad"><div style={{ maxWidth: 1080, margin: "0 auto" }}><div style={{ textAlign: "center" }}><div style={eyebrow}>SIMPLE PRICING</div><h2 style={{ ...heading, marginLeft: "auto", marginRight: "auto" }}>Start free.<br />Grow when you're ready.</h2><p style={{ ...lead, marginLeft: "auto", marginRight: "auto" }}>Choose the workspace that fits the way you work.</p></div><div className="thrive-plan-grid" style={{ marginTop: 30, display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 14, alignItems: "stretch" }}>{plans.map(plan => <article key={plan.name} style={{ ...panel, padding: 22, position: "relative", overflow: "hidden", border: plan.popular ? "2px solid #8B1E3F" : "1px solid #D5CEC7", boxShadow: plan.popular ? "0 18px 38px rgba(139,30,63,.14)" : "0 12px 28px rgba(47,58,63,.07)" }}>{plan.popular && <div style={{ margin: "-22px -22px 18px", padding: "7px 10px", background: "#8B1E3F", color: "#FFF", textAlign: "center", fontSize: 9, fontWeight: 900, letterSpacing: 1.2, textTransform: "uppercase" }}>Most popular</div>}<h3 style={{ margin: 0, fontSize: 18 }}>{plan.name}</h3><div style={{ marginTop: 13, display: "flex", alignItems: "baseline", gap: 4 }}><strong style={{ fontSize: 31 }}>{plan.price}</strong><span style={{ color: "#7A8184", fontSize: 10 }}>{plan.period}</span></div><p style={{ minHeight: 58, margin: "8px 0 15px", color: "#687178", fontSize: 11.5, lineHeight: 1.5 }}>{plan.description}</p><div style={{ display: "grid", gap: 8 }}>{plan.features.map(feature => <div key={feature} style={{ display: "flex", gap: 7, fontSize: 11.5, lineHeight: 1.35 }}><span style={{ color: "#8B1E3F", fontWeight: 900 }}>✓</span>{feature}</div>)}</div><button type="button" onClick={goPricing} style={{ width: "100%", marginTop: 20, minHeight: 40, border: plan.popular ? "none" : "1px solid #CEC6BF", borderRadius: 9, background: plan.popular ? "#8B1E3F" : "#FFF", color: plan.popular ? "#FFF" : "#2F3A3F", fontWeight: 850, fontSize: 11.5, cursor: "pointer" }}>{plan.name === "Free Workspace" ? "Start Free →" : `Choose ${plan.name.replace(" Workspace", "")} →`}</button></article>)}</div><div style={{ marginTop: 15, textAlign: "center", color: "#7A8184", fontSize: 10.5 }}>Development pricing only — billing and account subscriptions will be connected next.</div></div></section>
      <section style={{ background: "#2F3A3F", color: "#FFF", padding: "60px 22px" }}><div style={{ maxWidth: 760, margin: "0 auto", textAlign: "center" }}><div style={eyebrowDark}>READY TO THRIVE?</div><h2 style={{ margin: "10px 0 0", fontSize: "clamp(31px,5vw,48px)", lineHeight: 1.06 }}>Less admin.<br />More time for your business.</h2><p style={{ margin: "13px auto 0", maxWidth: 560, color: "#C7CDCF", fontSize: 13.5, lineHeight: 1.55 }}>Start with THRIVE Free and move up when you need more.</p><div style={{ marginTop: 22, display: "flex", justifyContent: "center", gap: 10, flexWrap: "wrap" }}><CtaButton onClick={goPricing}>Start Free →</CtaButton><CtaButton secondary onClick={() => scrollToId("features")}>View Features</CtaButton></div></div></section>
    </main>
    <footer style={{ background: "#232C30", color: "#AEB6B9", padding: "28px 22px" }}><div style={{ maxWidth: 1080, margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 24, flexWrap: "wrap" }}><div><Logo /><div style={{ marginTop: 8, fontSize: 10.5 }}>Streamline your business. Simplify your work.</div></div><div style={{ display: "flex", gap: 18, flexWrap: "wrap", fontSize: 11 }}><a href="/thrive/terms" style={{ color: "#C7CDCF", textDecoration: "none" }}>Terms &amp; Conditions</a><a href="/thrive/privacy" style={{ color: "#C7CDCF", textDecoration: "none" }}>Privacy Policy</a></div><div style={{ width: "100%", borderTop: "1px solid rgba(255,255,255,.08)", paddingTop: 15, fontSize: 10 }}>© {new Date().getFullYear()} THRIVE. All rights reserved.</div></div></footer>
  </div>;
}
